version: '3.8'

services:
  mongoDocker:
    image: mongo:5
    command: mongod --replSet myReplicaSet --bind_ip localhost,mongoDocker
    volumes:
      - mongoMainVol:/data/db
    ports:
      - "27017:27017"
    networks:
      - mongoCluster

  mongoDocRep1:
    image: mongo:5
    command: mongod --replSet myReplicaSet --bind_ip localhost,mongoDocRep1
    volumes:
      - mongoSec1Vol:/data/db
    ports:
      - "27018:27017"
    networks:
      - mongoCluster

  mongoDocRep2:
    image: mongo:5
    command: mongod --replSet myReplicaSet --bind_ip localhost,mongoDocRep2
    volumes:
      - mongoSec2Vol:/data/db
    ports:
      - "27019:27017"
    networks:
      - mongoCluster

  polybot:
    image: kinanhino/polybot:1.0.1
    #build: ./polybot
    env_file: .env_poly
    ports:
      - "8443:8443"
    networks:
      - mongoCluster

  yolo:
    image: kinanhino/yolobot:1.0.0
    env_file: .env_yolo
    ports:
      - "8081:8081"
    networks:
      - mongoCluster

networks:
  mongoCluster:
    driver: bridge

volumes:
  mongoMainVol:
  mongoSec1Vol:
  mongoSec2Vol: